# Action to set up the build environment for this repository. You'll have to
# clone the repository first; we don't do that here.

name: "Setup"
author: "Ammar Ratnani <ammrat13@gmail.com>"
description: "Set up the build environment for `ammrat13.org`"

runs:
  using: "composite"
  steps:

    - name: "Set up Ruby"
      uses: "ruby/setup-ruby@v1"
      with:
        ruby-version: "3.3"
        bundler-cache: true

    - name: "Set up Node.js"
      uses: "actions/setup-node@v6"
      with:
        node-version: "22"
        cache: "npm"

    - name: "Install Node.js dependencies"
      shell: "bash"
      run: |
        npm ci
