# Check that the site builds and that links are not broken

name: "Build and Test"
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:

      - name: "Checkout"
        uses: "actions/checkout@v6"

      - name: "Setup"
        uses: "./.github/actions/setup"

      - name: "Generate HTML"
        uses: "./.github/actions/build"

      - name: "Run visual regression tests"
        run: |
          npx percy snapshot ./_site
        env:
          PERCY_TOKEN: "${{ secrets.PERCY_TOKEN }}"
          PERCY_SKIP_UPDATE_CHECK: "true"
        timeout-minutes: 5

      - name: "Check for broken links"
        uses: "./.github/actions/link-test"
        timeout-minutes: 2
