# Every week, check that the links are not broken.

name: "Check Links"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  check-links:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"

      - name: "Setup"
        uses: "./.github/actions/setup"

      - name: "Generate HTML"
        uses: "./.github/actions/build"

      - name: "Check for broken links"
        uses: "./.github/actions/link-test"
        timeout-minutes: 2
