# Every day, force a rebuild of the site. This is needed to publish posts that
# were initially "posted" in the future.

name: "Publish"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  publish:
    runs-on: "ubuntu-slim"
    timeout-minutes: 1
    steps:
      - name: "Force site rebuild"
        run: |
          curl \
            "https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/pages/projects/${PROJECT_NAME}/deployments" \
            --request POST \
            --header "Authorization: Bearer ${TOKEN}" \
            --header "Content-Type: application/json;charset=utf-8" \
            --fail-with-body
        env:
          ACCOUNT_ID: "${{ vars.CLOUDFLARE_ACCOUNT_ID }}"
          PROJECT_NAME: "${{ vars.CLOUDFLARE_PAGES_PROJECT_NAME }}"
          TOKEN: "${{ secrets.CLOUDFLARE_PAGES_TOKEN }}"
